### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by gavrilikhin-d** [gavrilikhin-d/libos#3]
Sadly, I don't have a MacBook at the moment. If someone has it and is ready to help - I would be very thankful.

**Comment by singhsanskar202** [comment]
Yes I have macbook air. Can I work on it.

**Comment by gavrilikhin-d** [comment]
Thanks! I'll appreciate it.

**Comment by gavrilikhin-d** [comment]
Started working on it. This one is in priority.

**Comment by gavrilikhin-d** [comment]
Added in #17
